version: "3.7"

services:
  nginx:
    image: nginx:1.17-alpine
    container_name: app-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./.docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app

  php-fpm:
    build:
      args:
        user: felipe
        uid: 1000
      context: ./.docker/php
      dockerfile: Dockerfile
    container_name: app-php-fpm
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app

networks:
  app:
    driver: bridge
